services:
- docker
env:
  global:
  - DOCKER_VERSION=17.07.0~ce-0~ubuntu
  - DOCKER_COMPOSE_VERSION=1.14.0
before_install:
- openssl aes-256-cbc -K $encrypted_92b3f22fea64_key -iv $encrypted_92b3f22fea64_iv
  -in tls.tar.enc -out tls.tar -d
- set -e
- tar xvf tls.tar
- travisci/install_docker.sh
script:
- docker-compose build --build-arg RUN_TESTS=1 api
- docker-compose up -d
after_script:
- docker-compose down
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag dotbook_api:latest nojnhuh/dotbook-api:latest
- docker push nojnhuh/dotbook-api:latest
notifications:
  email:
    on_success: never
    on_failure: never
