services:
- docker
env:
  global:
  - DOCKER_VERSION=17.07.0~ce-0~ubuntu
  - DOCKER_COMPOSE_VERSION=1.14.0
  - IMAGE_NAME=nojnhuh/dotbook-api
  - IMAGE_TAG=$TRAVIS_BRANCH-$TRAVIS_COMMIT
before_install:
- travisci/install_docker.sh
script:
- docker-compose build --build-arg RUN_TESTS=1 api
- docker-compose up -d
after_script:
- docker-compose down
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
# - docker tag dotbook_api:latest $IMAGE_NAME:$IMAGE_TAG
- docker tag dotbook_api:latest $IMAGE_NAME:latest
# - docker push $IMAGE_NAME:$IMAGE_TAG
- docker push $IMAGE_NAME:latest
notifications:
  email:
    on_success: never
    on_failure: never
