language: go

services:
  - docker

go:
  - 1.x
  - 1.8
  - master

before_install:
  - docker --version
  - docker-compose --version

script:
  - go test -v ./...
  - docker-compose build --no-cache

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker-compose push;
  fi


notifications:
  email:
    on_success: never
    on_failure: never
