version: '3'
services:
  api:
    build: 
      context: .
    links:
      - db:database
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_DB_HOST=database
      - DB_DB_PORT=27017
  db:
    image: "mongo:3.4"
    volumes:
      - ./.dbdata:/data/db
