apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.http.externalPort }}
    targetPort: {{ .Values.service.ports.http.internalPort }}
    protocol: TCP
    name: {{ .Values.service.ports.http.name }}
  selector:
      app: {{ template "fullname" . }}
